export const laws = [
  {
    id: "1",
    title: "Title 1",
    description: "Description 1",
    content: "Content 1",
    tagline: "Tagline for Title 1",
  },
  {
    id: "2",
    title: "Title 2",
    description: "Description 2",
    content: "Content 2",
    tagline: "Tagline for Title 2",
  },
  {
    id: "3",
    title: "Title 3",
    description: "Description 3",
    content: "Content 3",
    tagline: "Tagline for Title 3",
  },
  {
    id: "4",
    title: "Title 4",
    description: "Description 4",
    content: "Content 4",
    tagline: "Tagline for Title 4",
  },
  {
    id: "5",
    title: "Title 5",
    description: "Description 5",
    content: "Content 5",
    tagline: "Tagline for Title 5",
  },
  {
    id: "6",
    title: "Title 6",
    description: "Description 6",
    content: "Content 6",
    tagline: "Tagline for Title 6",
  },
  {
    id: "7",
    title: "Title 7",
    description: "Description 7",
    content: "Content 7",
    tagline: "Tagline for Title 7",
  },
  {
    id: "8",
    title: "Title 8",
    description: "Description 8",
    content: "Content 8",
    tagline: "Tagline for Title 8",
  },
  {
    id: "9",
    title: "Title 9",
    description: "Description 9",
    content: "Content 9",
    tagline: "Tagline for Title 9",
  },
  {
    id: "10",
    title: "Title 10",
    description: "Description 10",
    content: "Content 10",
    tagline: "Tagline for Title 10",
  },
  {
    id: "11",
    title: "Title 11",
    description: "Description 11",
    content: "Content 11",
    tagline: "Tagline for Title 11",
  },
  {
    id: "12",
    title: "Title 12",
    description: "Description 12",
    content: "Content 12",
    tagline: "Tagline for Title 12",
  },
  {
    id: "13",
    title: "Title 13",
    description: "Description 13",
    content: "Content 13",
    tagline: "Tagline for Title 13",
  },
  {
    id: "14",
    title: "Title 14",
    description: "Description 14",
    content: "Content 14",
    tagline: "Tagline for Title 14",
  },
  {
    id: "15",
    title: "Title 15",
    description: "Description 15",
    content: "Content 15",
    tagline: "Tagline for Title 15",
  },
  {
    id: "16",
    title: "Title 16",
    description: "Description 16",
    content: "Content 16",
    tagline: "Tagline for Title 16",
  },
  {
    id: "17",
    title: "Title 17",
    description: "Description 17",
    content: "Content 17",
    tagline: "Tagline for Title 17",
  },
  {
    id: "18",
    title: "Title 18",
    description: "Description 18",
    content: "Content 18",
    tagline: "Tagline for Title 18",
  },
  {
    id: "19",
    title: "Title 19",
    description: "Description 19",
    content: "Content 19",
    tagline: "Tagline for Title 19",
  },
  {
    id: "20",
    title: "Title 20",
    description: "Description 20",
    content: "Content 20",
    tagline: "Tagline for Title 20",
  },
  {
    id: "21",
    title: "Title 21",
    description: "Description 21",
    content: "Content 21",
    tagline: "Tagline for Title 21",
  },
  {
    id: "22",
    title: "Title 22",
    description: "Description 22",
    content: "Content 22",
    tagline: "Tagline for Title 22",
  },
  {
    id: "23",
    title: "Title 23",
    description: "Description 23",
    content: "Content 23",
    tagline: "Tagline for Title 23",
  },
  {
    id: "24",
    title: "Title 24",
    description: "Description 24",
    content: "Content 24",
    tagline: "Tagline for Title 24",
  },
  {
    id: "25",
    title: "Title 25",
    description: "Description 25",
    content: "Content 25",
    tagline: "Tagline for Title 25",
  },
  {
    id: "26",
    title: "Title 26",
    description: "Description 26",
    content: "Content 26",
    tagline: "Tagline for Title 26",
  },
  {
    id: "27",
    title: "Title 27",
    description: "Description 27",
    content: "Content 27",
    tagline: "Tagline for Title 27",
  },
  {
    id: "28",
    title: "Title 28",
    description: "Description 28",
    content: "Content 28",
    tagline: "Tagline for Title 28",
  },
  {
    id: "29",
    title: "Title 29",
    description: "Description 29",
    content: "Content 29",
    tagline: "Tagline for Title 29",
  },
  {
    id: "30",
    title: "Title 30",
    description: "Description 30",
    content: "Content 30",
    tagline: "Tagline for Title 30",
  },
  {
    id: "31",
    title: "Title 31",
    description: "Description 31",
    content: "Content 31",
    tagline: "Tagline for Title 31",
  },
  {
    id: "32",
    title: "Title 32",
    description: "Description 32",
    content: "Content 32",
    tagline: "Tagline for Title 32",
  },
  {
    id: "33",
    title: "Title 33",
    description: "Description 33",
    content: "Content 33",
    tagline: "Tagline for Title 33",
  },
  {
    id: "34",
    title: "Title 34",
    description: "Description 34",
    content: "Content 34",
    tagline: "Tagline for Title 34",
  },
  {
    id: "35",
    title: "Title 35",
    description: "Description 35",
    content: "Content 35",
    tagline: "Tagline for Title 35",
  },
  {
    id: "36",
    title: "Title 36",
    description: "Description 36",
    content: "Content 36",
    tagline: "Tagline for Title 36",
  },
  {
    id: "37",
    title: "Title 37",
    description: "Description 37",
    content: "Content 37",
    tagline: "Tagline for Title 37",
  },
  {
    id: "38",
    title: "Title 38",
    description: "Description 38",
    content: "Content 38",
    tagline: "Tagline for Title 38",
  },
  {
    id: "39",
    title: "Title 39",
    description: "Description 39",
    content: "Content 39",
    tagline: "Tagline for Title 39",
  },
  {
    id: "40",
    title: "Title 40",
    description: "Description 40",
    content: "Content 40",
    tagline: "Tagline for Title 40",
  },
  {
    id: "41",
    title: "Title 41",
    description: "Description 41",
    content: "Content 41",
    tagline: "Tagline for Title 41",
  },
  {
    id: "42",
    title: "Title 42",
    description: "Description 42",
    content: "Content 42",
    tagline: "Tagline for Title 42",
  },
  {
    id: "43",
    title: "Title 43",
    description: "Description 43",
    content: "Content 43",
    tagline: "Tagline for Title 43",
  },
  {
    id: "44",
    title: "Title 44",
    description: "Description 44",
    content: "Content 44",
    tagline: "Tagline for Title 44",
  },
  {
    id: "45",
    title: "Title 45",
    description: "Description 45",
    content: "Content 45",
    tagline: "Tagline for Title 45",
  },
  {
    id: "46",
    title: "Title 46",
    description: "Description 46",
    content: "Content 46",
    tagline: "Tagline for Title 46",
  },
  {
    id: "47",
    title: "Title 47",
    description: "Description 47",
    content: "Content 47",
    tagline: "Tagline for Title 47",
  },
  {
    id: "48",
    title: "Title 48",
    description: "Description 48",
    content: "Content 48",
    tagline: "Tagline for Title 48",
  },
  {
    id: "49",
    title: "Title 49",
    description: "Description 49",
    content: "Content 49",
    tagline: "Tagline for Title 49",
  },
  {
    id: "50",
    title: "Title 50",
    description: "Description 50",
    content: "Content 50",
    tagline: "Tagline for Title 50",
  },
  {
    id: "51",
    title: "Title 51",
    description: "Description 51",
    content: "Content 51",
    tagline: "Tagline for Title 51",
  },
  {
    id: "52",
    title: "Title 52",
    description: "Description 52",
    content: "Content 52",
    tagline: "Tagline for Title 52",
  },
  {
    id: "53",
    title: "Title 53",
    description: "Description 53",
    content: "Content 53",
    tagline: "Tagline for Title 53",
  },
  {
    id: "54",
    title: "Title 54",
    description: "Description 54",
    content: "Content 54",
    tagline: "Tagline for Title 54",
  },
  {
    id: "55",
    title: "Title 55",
    description: "Description 55",
    content: "Content 55",
    tagline: "Tagline for Title 55",
  },
  {
    id: "56",
    title: "Title 56",
    description: "Description 56",
    content: "Content 56",
    tagline: "Tagline for Title 56",
  },
  {
    id: "57",
    title: "Title 57",
    description: "Description 57",
    content: "Content 57",
    tagline: "Tagline for Title 57",
  },
  {
    id: "58",
    title: "Title 58",
    description: "Description 58",
    content: "Content 58",
    tagline: "Tagline for Title 58",
  },
  {
    id: "59",
    title: "Title 59",
    description: "Description 59",
    content: "Content 59",
    tagline: "Tagline for Title 59",
  },
  {
    id: "60",
    title: "Title 60",
    description: "Description 60",
    content: "Content 60",
    tagline: "Tagline for Title 60",
  },
  {
    id: "61",
    title: "Title 61",
    description: "Description 61",
    content: "Content 61",
    tagline: "Tagline for Title 61",
  },
  {
    id: "62",
    title: "Title 62",
    description: "Description 62",
    content: "Content 62",
    tagline: "Tagline for Title 62",
  },
  {
    id: "63",
    title: "Title 63",
    description: "Description 63",
    content: "Content 63",
    tagline: "Tagline for Title 63",
  },
  {
    id: "64",
    title: "Title 64",
    description: "Description 64",
    content: "Content 64",
    tagline: "Tagline for Title 64",
  },
  {
    id: "65",
    title: "Title 65",
    description: "Description 65",
    content: "Content 65",
    tagline: "Tagline for Title 65",
  },
  {
    id: "66",
    title: "Title 66",
    description: "Description 66",
    content: "Content 66",
    tagline: "Tagline for Title 66",
  },
  {
    id: "67",
    title: "Title 67",
    description: "Description 67",
    content: "Content 67",
    tagline: "Tagline for Title 67",
  },
  {
    id: "68",
    title: "Title 68",
    description: "Description 68",
    content: "Content 68",
    tagline: "Tagline for Title 68",
  },
  {
    id: "69",
    title: "Title 69",
    description: "Description 69",
    content: "Content 69",
    tagline: "Tagline for Title 69",
  },
  {
    id: "70",
    title: "Title 70",
    description: "Description 70",
    content: "Content 70",
    tagline: "Tagline for Title 70",
  },
  {
    id: "71",
    title: "Title 71",
    description: "Description 71",
    content: "Content 71",
    tagline: "Tagline for Title 71",
  },
  {
    id: "72",
    title: "Title 72",
    description: "Description 72",
    content: "Content 72",
    tagline: "Tagline for Title 72",
  },
  {
    id: "73",
    title: "Title 73",
    description: "Description 73",
    content: "Content 73",
    tagline: "Tagline for Title 73",
  },
  {
    id: "74",
    title: "Title 74",
    description: "Description 74",
    content: "Content 74",
    tagline: "Tagline for Title 74",
  },
  {
    id: "75",
    title: "Title 75",
    description: "Description 75",
    content: "Content 75",
    tagline: "Tagline for Title 75",
  },
  {
    id: "76",
    title: "Title 76",
    description: "Description 76",
    content: "Content 76",
    tagline: "Tagline for Title 76",
  },
  {
    id: "77",
    title: "Title 77",
    description: "Description 77",
    content: "Content 77",
    tagline: "Tagline for Title 77",
  },
  {
    id: "78",
    title: "Title 78",
    description: "Description 78",
    content: "Content 78",
    tagline: "Tagline for Title 78",
  },
  {
    id: "79",
    title: "Title 79",
    description: "Description 79",
    content: "Content 79",
    tagline: "Tagline for Title 79",
  },
  {
    id: "80",
    title: "Title 80",
    description: "Description 80",
    content: "Content 80",
    tagline: "Tagline for Title 80",
  },
  {
    id: "81",
    title: "Title 81",
    description: "Description 81",
    content: "Content 81",
    tagline: "Tagline for Title 81",
  },
  {
    id: "82",
    title: "Title 82",
    description: "Description 82",
    content: "Content 82",
    tagline: "Tagline for Title 82",
  },
  {
    id: "83",
    title: "Title 83",
    description: "Description 83",
    content: "Content 83",
    tagline: "Tagline for Title 83",
  },
  {
    id: "84",
    title: "Title 84",
    description: "Description 84",
    content: "Content 84",
    tagline: "Tagline for Title 84",
  },
];

export const index = [
  {
    id: "1",
    title: "MỤC 1",
  },
  {
    id: "2",
    title: "MỤC 2",
  },
  {
    id: "3",
    title: "MỤC 3",
  },
  {
    id: "4",
    title: "MỤC 4",
  },
  {
    id: "5",
    title: "MỤC 5",
  },
  {
    id: "6",
    title: "MỤC 6",
  },
  {
    id: "7",
    title: "MỤC 7",
  },
];
